namespace Cogito;

/// Typed action/procedure mutation for ReplayCalc. Scalar policy counters and
/// per-action solve results are bounded replacements; procedure inputs,
/// counterexamples, and obligation-search entries are likewise explicit typed
/// replacements so replay never smuggles an opaque serialized image through the
/// mutation rail.
internal readonly record struct EmlActionObligationSearchDelta(
    EmlPredictionID PredictionID,
    int Epoch,
    int Attempts);

internal readonly record struct EmlActionCheckpointDelta(
    EmlActionSelections Selection,
    ulong ActionRng,
    int ActionDecision,
    int RoundRobinCursor,
    int ActionEnumTaken,
    int ActionEnumRuler,
    bool ActionEnumDone,
    OutcomeArmState[] ArmStates,
    int PendingArmIndex,
    EmlActionArms CurrentActionArm,
    int[] ActionOffers,
    long[] ActionEvaluatorCalls,
    int[] ActionFirstCaptures,
    double[] ActionDeltaOutcomes,
    int StressCursor,
    int StressExactTests,
    int StressExactRefuted,
    int StressAsymptoticTests,
    int StressAsymptoticRefuted,
    int StressControlTests,
    int StressControlRefuted,
    string[] Counterexamples,
    string? PendingCounterexample,
    int[] SelectionCauses,
    int ActionFallbacks,
    double ActionGlobalYield,
    int ActionGlobalOutcomes,
    long SharedCanonicalDeltas,
    long SharedFirstCaptures,
    CortexProcedureCheckpointState? Procedure,
    int ProcedureSolveDeltaCursor,
    EmlCertificateDelta[] ProcedureSolveDeltas,
    int ProceduresStarted,
    int ProceduresCompleted,
    int ProcedureBindings,
    int ProcedureShuffledBindings,
    int ProcedureObligationMatches,
    int ProcedureNewDeltas,
    int ProcedureGuardsPassed,
    int ProcedureGuardsSkipped,
    int ProcedureGuardsAbstained,
    int ProcedureCanonicalDeltas,
    int HoleCursor,
    double IntrinsicFrontierResidual,
    bool ActionBatchHadCanonicalDelta,
    int DiscoveryEpoch,
    EmlActionObligationSearchDelta[] ObligationSearch,
    int ObligationSearchAttempts,
    int ObligationSearchSuppressions,
    int ObligationSearchRevivals,
    int ObligationSuppressedCalls,
    int ExecutionAdmissions,
    int ExecutionAffirmSkips,
    int HypothesisCapSkips,
    int FirstGenerativeDecision,
    int FirstGenerativeStep,
    EmlActionObligationSearchDelta[] ObligationSearchUpdates,
    EmlPredictionID[] ObligationSearchRemovals,
    string[] CounterexampleUpdates);
